version: '1.0.0-beta1.{build}'
image: Visual Studio 2017

branches:
  only:
  - master

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CLI_CHANNEL: release/2.0.0
  CLI_VERSION: 2.0.0-preview2-006497
  nodejs_version: "8"

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

install:
  # Install NodeJS 8.0
  - ps: Install-Product node $env:nodejs_version
  # Install .net SDK
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/release/2.0.0-preview2/scripts/obtain/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Channel $env:CLI_CHANNEL -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./build.ps1 -target Test

on_success:
  - ps: ./build.ps1 -target ExportCoverageReport

artifacts:
  - sejil/nuget-build/*.nupkg

deploy:
